#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : font-util
Version  : 1.3.3
Release  : 15
URL      : https://www.x.org/releases/individual/font/font-util-1.3.3.tar.gz
Source0  : https://www.x.org/releases/individual/font/font-util-1.3.3.tar.gz
Source1  : https://www.x.org/releases/individual/font/font-util-1.3.3.tar.gz.sig
Summary  : Font utilities dirs
Group    : Development/Tools
License  : BSD-2-Clause
Requires: font-util-bin = %{version}-%{release}
Requires: font-util-data = %{version}-%{release}
Requires: font-util-license = %{version}-%{release}
Requires: font-util-man = %{version}-%{release}
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkg-config
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(xorg-macros)

%description
X.Org font package creation/installation utilities
--------------------------------------------------

%package bin
Summary: bin components for the font-util package.
Group: Binaries
Requires: font-util-data = %{version}-%{release}
Requires: font-util-license = %{version}-%{release}

%description bin
bin components for the font-util package.


%package data
Summary: data components for the font-util package.
Group: Data

%description data
data components for the font-util package.


%package dev
Summary: dev components for the font-util package.
Group: Development
Requires: font-util-bin = %{version}-%{release}
Requires: font-util-data = %{version}-%{release}
Provides: font-util-devel = %{version}-%{release}
Requires: font-util = %{version}-%{release}

%description dev
dev components for the font-util package.


%package dev32
Summary: dev32 components for the font-util package.
Group: Default
Requires: font-util-bin = %{version}-%{release}
Requires: font-util-data = %{version}-%{release}
Requires: font-util-dev = %{version}-%{release}

%description dev32
dev32 components for the font-util package.


%package license
Summary: license components for the font-util package.
Group: Default

%description license
license components for the font-util package.


%package man
Summary: man components for the font-util package.
Group: Default

%description man
man components for the font-util package.


%prep
%setup -q -n font-util-1.3.3
cd %{_builddir}/font-util-1.3.3
pushd ..
cp -a font-util-1.3.3 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1657656210
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../build32;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1657656210
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/font-util
cp %{_builddir}/font-util-1.3.3/COPYING %{buildroot}/usr/share/package-licenses/font-util/759423cdfc761cbbf5ac28dc6f0b7b825fa32b14
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bdftruncate
/usr/bin/ucs2any

%files data
%defattr(-,root,root,-)
/usr/share/fonts/X11/util/map-ISO8859-1
/usr/share/fonts/X11/util/map-ISO8859-10
/usr/share/fonts/X11/util/map-ISO8859-11
/usr/share/fonts/X11/util/map-ISO8859-13
/usr/share/fonts/X11/util/map-ISO8859-14
/usr/share/fonts/X11/util/map-ISO8859-15
/usr/share/fonts/X11/util/map-ISO8859-16
/usr/share/fonts/X11/util/map-ISO8859-2
/usr/share/fonts/X11/util/map-ISO8859-3
/usr/share/fonts/X11/util/map-ISO8859-4
/usr/share/fonts/X11/util/map-ISO8859-5
/usr/share/fonts/X11/util/map-ISO8859-6
/usr/share/fonts/X11/util/map-ISO8859-7
/usr/share/fonts/X11/util/map-ISO8859-8
/usr/share/fonts/X11/util/map-ISO8859-9
/usr/share/fonts/X11/util/map-JISX0201.1976-0
/usr/share/fonts/X11/util/map-KOI8-R

%files dev
%defattr(-,root,root,-)
/usr/lib64/pkgconfig/fontutil.pc
/usr/share/aclocal/*.m4

%files dev32
%defattr(-,root,root,-)
/usr/lib32/pkgconfig/32fontutil.pc
/usr/lib32/pkgconfig/fontutil.pc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/font-util/759423cdfc761cbbf5ac28dc6f0b7b825fa32b14

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/bdftruncate.1
/usr/share/man/man1/ucs2any.1
