#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : font-util
Version  : 1.3.1
Release  : 11
URL      : http://xorg.freedesktop.org/releases/individual/font/font-util-1.3.1.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/font/font-util-1.3.1.tar.gz
Summary  : Font utilities dirs
Group    : Development/Tools
License  : BSD-2-Clause
Requires: font-util-bin
Requires: font-util-data
Requires: font-util-doc
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(xorg-macros)

%description
X.Org font package creation/installation utilities
If the --with-fontrootdir option is specified when configuring this
package, it will be recorded in the fontutil pkg-config file to be used
as the default parent directory for font modules built using the fontutil
macros from version 1.1 or later of this package.

%package bin
Summary: bin components for the font-util package.
Group: Binaries
Requires: font-util-data

%description bin
bin components for the font-util package.


%package data
Summary: data components for the font-util package.
Group: Data

%description data
data components for the font-util package.


%package dev
Summary: dev components for the font-util package.
Group: Development
Requires: font-util-bin
Requires: font-util-data
Provides: font-util-devel

%description dev
dev components for the font-util package.


%package dev32
Summary: dev32 components for the font-util package.
Group: Default
Requires: font-util-bin
Requires: font-util-data

%description dev32
dev32 components for the font-util package.


%package doc
Summary: doc components for the font-util package.
Group: Documentation

%description doc
doc components for the font-util package.


%prep
%setup -q -n font-util-1.3.1
pushd ..
cp -a font-util-1.3.1 build32
popd

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

pushd ../build32
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
%configure --disable-static  --libdir=/usr/lib32
make V=1  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
pushd ../build32
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do mv $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bdftruncate
/usr/bin/ucs2any

%files data
%defattr(-,root,root,-)
/usr/share/fonts/X11/util/map-ISO8859-1
/usr/share/fonts/X11/util/map-ISO8859-10
/usr/share/fonts/X11/util/map-ISO8859-11
/usr/share/fonts/X11/util/map-ISO8859-13
/usr/share/fonts/X11/util/map-ISO8859-14
/usr/share/fonts/X11/util/map-ISO8859-15
/usr/share/fonts/X11/util/map-ISO8859-16
/usr/share/fonts/X11/util/map-ISO8859-2
/usr/share/fonts/X11/util/map-ISO8859-3
/usr/share/fonts/X11/util/map-ISO8859-4
/usr/share/fonts/X11/util/map-ISO8859-5
/usr/share/fonts/X11/util/map-ISO8859-6
/usr/share/fonts/X11/util/map-ISO8859-7
/usr/share/fonts/X11/util/map-ISO8859-8
/usr/share/fonts/X11/util/map-ISO8859-9
/usr/share/fonts/X11/util/map-JISX0201.1976-0
/usr/share/fonts/X11/util/map-KOI8-R

%files dev
%defattr(-,root,root,-)
/usr/lib64/pkgconfig/fontutil.pc
/usr/share/aclocal/*.m4

%files dev32
%defattr(-,root,root,-)
/usr/lib32/pkgconfig/32fontutil.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
